name: Run Program

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_program:
    name: Test SP1 Helios Program
    runs-on: ubuntu-latest
    environment: test_program
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      SOURCE_CONSENSUS_RPC_URL: ${{ secrets.SOURCE_CONSENSUS_RPC_URL }}
      SOURCE_CHAIN_ID: ${{ vars.SOURCE_CHAIN_ID }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version
          source ~/.bashrc
      - name: Run test
        run: |
          cd script
          cargo run --bin test --release
       
