name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose
    
    - name: Check code formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check
        
    - name: Check clippy lints
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace -- -D warnings
